import React, { useEffect, useState } from 'react';
import Tree from 'antd/es/tree/Tree';
import { message } from 'antd';
import type { DataNode, TreeProps } from 'antd/es/tree';
export default ({ json_datas }: { json_datas: Array<any> }) => {
  const [value, setValue] = useState(Array<any>);
  const json_data: Array<any> = [
    {
      taskId: 1,
      taskTitle: '(一）优质资源扩面行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 2,
      taskTitle: '(二）育人质量提质行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 3,
      taskTitle: '(三）办学活力激发行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 4,
      taskTitle: '(四）综合素质提升行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 5,
      taskTitle: '(五）综合评价改革行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 6,
      taskTitle: '(六）教育合作深化行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 7,
      taskTitle: '(七）普惠资源优享行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 8,
      taskTitle: '(八）城乡师资共进行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 9,
      taskTitle: '(九）教育数智赋能行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 10,
      taskTitle: '(十）教育平安护航行动',
      taskInfo: null,
      taskLevel: 1,
      taskParentId: 0,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 11,
      taskTitle: '1.实施学前教育“上好园”工程',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 1,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 12,
      taskTitle: '2.实施义务教育“优质强校”工程',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 1,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 13,
      taskTitle: '3.实施普高“特色升级”工程',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 1,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 14,
      taskTitle: '4.实施特殊教育“融合融通”工程',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 1,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 15,
      taskTitle: '5.打造幼儿园课程品牌',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 2,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 16,
      taskTitle: '6.推进中小学课程教学改革',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 2,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 17,
      taskTitle: '7.推动“双减”强能提质',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 2,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 18,
      taskTitle: '8.推进各学段“衔接融通”',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 2,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 19,
      taskTitle: '9.落实中小学校党组织领导的校长负责制',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 3,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 20,
      taskTitle: '10.增强学校办学自主权',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 3,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 21,
      taskTitle: '11.开展大中小思政课一体化建设',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 4,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 22,
      taskTitle: '12.完善“一人一技、一生一艺”培养体系',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 4,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 23,
      taskTitle: '13.建立全学习周期成长指导机制',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 4,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 24,
      taskTitle: '14.构建立体评价体系',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 5,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 25,
      taskTitle: '15.探索招生考试改革',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 5,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 26,
      taskTitle: '16.强化督导问效',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 5,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 27,
      taskTitle: '17.推进基础教育公共服务共建共享',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 6,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 28,
      taskTitle: '18.打造基础教育国际交流新枢纽',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 6,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 29,
      taskTitle: '19.公办学位增量扩容',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 7,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 30,
      taskTitle: '20.投入保障提效增质',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 7,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 31,
      taskTitle: '21.随迁子女同城同待',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 7,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 32,
      taskTitle: '22.推进教师资源配置改革',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 8,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 33,
      taskTitle: '23.健全师德师风约束机制',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 8,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 34,
      taskTitle: '24.保障教师待遇固基扩面',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 8,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 35,
      taskTitle: '25.全面提升教育教学能力水平',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 8,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 36,
      taskTitle: '26.创新乡村教师支持机制',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 8,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 37,
      taskTitle: '27.强化数字化基础建设',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 9,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 38,
      taskTitle: '28.加快数字化资源共享',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 9,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 39,
      taskTitle: '29.推进数字化业态重塑',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 9,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 40,
      taskTitle: '30.强化校园安全教育',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 10,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 41,
      taskTitle: '31.完善风险防控体系',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 10,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
    {
      taskId: 42,
      taskTitle: '32.健全安全保障体系',
      taskInfo: null,
      taskLevel: 2,
      taskParentId: 10,
      taskRule: null,
      gmtCreate: null,
      gmtModify: null,
      isDeleted: 0,
      createBy: null,
      taskUser: null,
      taskDept: null,
      children: null,
    },
  ];
  const array2tree = (res: Array<any>) => {
    const newList: Array<any> = [];
    for (let i = 0; i < res.length; i++) {
      res[i].title = res[i].taskTitle;
      const list = res.filter((item) => item.taskId == res[i].taskParentId);
      if (list.length > 0) {
        const parent = list[0];
        parent.children = (parent.children || []).concat(res[i]);
      } else {
        newList.push(res[i]);
      }
    }
    setValue(newList);
    return newList;
  };
  useEffect(() => {
    array2tree(json_data);
  }, []);
  const onCheck: TreeProps['onCheck'] = (checkedKeys, info) => {
    console.log('onCheck', checkedKeys, info);
    const { title } = info.node;
    message.success(`已选择：${title}`);
  };
  return <Tree checkable onCheck={onCheck} treeData={value} />;
};
