import '@testing-library/jest-dom';
import React from 'react';
import { render, screen } from '@testing-library/react';
import TreeData from './index';

describe('<TreeData />', () => {
  it('render TreeData with dumi', () => {
    const msg = 'dumi';
    // interface jsonType{}
    const json_data: Array<any> = [
      {
        taskId: 1,
        taskTitle: '(一）优质资源扩面行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 2,
        taskTitle: '(二）育人质量提质行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 3,
        taskTitle: '(三）办学活力激发行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 4,
        taskTitle: '(四）综合素质提升行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 5,
        taskTitle: '(五）综合评价改革行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 6,
        taskTitle: '(六）教育合作深化行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 7,
        taskTitle: '(七）普惠资源优享行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 8,
        taskTitle: '(八）城乡师资共进行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 9,
        taskTitle: '(九）教育数智赋能行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 10,
        taskTitle: '(十）教育平安护航行动',
        taskInfo: null,
        taskLevel: 1,
        taskParentId: 0,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 11,
        taskTitle: '1.实施学前教育“上好园”工程',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 1,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 12,
        taskTitle: '2.实施义务教育“优质强校”工程',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 1,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 13,
        taskTitle: '3.实施普高“特色升级”工程',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 1,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 14,
        taskTitle: '4.实施特殊教育“融合融通”工程',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 1,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 15,
        taskTitle: '5.打造幼儿园课程品牌',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 2,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 16,
        taskTitle: '6.推进中小学课程教学改革',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 2,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 17,
        taskTitle: '7.推动“双减”强能提质',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 2,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 18,
        taskTitle: '8.推进各学段“衔接融通”',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 2,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 19,
        taskTitle: '9.落实中小学校党组织领导的校长负责制',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 3,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 20,
        taskTitle: '10.增强学校办学自主权',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 3,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 21,
        taskTitle: '11.开展大中小思政课一体化建设',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 4,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
      {
        taskId: 22,
        taskTitle: '12.完善“一人一技、一生一艺”培养体系',
        taskInfo: null,
        taskLevel: 2,
        taskParentId: 4,
        taskRule: null,
        gmtCreate: null,
        gmtModify: null,
        isDeleted: 0,
        createBy: null,
        taskUser: null,
        taskDept: null,
        children: null,
      },
    ];

    render(<TreeData json_datas={json_data} />);
    expect(screen.queryByText(msg)).toBeInTheDocument();
  });
});
